name: Bug Report
description: Report a reproducible defect or regression.
title: "[bug]: "
labels:
  - bug
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - API
        - Admin UI
        - Ingest Worker
        - Database
        - Docs
        - Other
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the problem.
      placeholder: What is broken?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Include exact commands, requests, and payloads if possible.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Environment / Context
      description: OS, Node version, Docker status, and logs.
